apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jijisa-win10
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: pengrixio
