apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win10-golden-disk
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: pengrixio
