---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: win10-golden-vm
  labels:
    name: win10-golden-vm
    kubevirt.io/os: win10
spec:
  domain:
    clock:
      timezone: "Asia/Seoul"
    features:
      acpi: {}
      apic: {}
    machine:
      type: ""
    cpu:
      cores: 4
    resources:
      requests:
        memory: 4Gi
    devices:
      disks:
      - name: win10-disk
        bootOrder: 2
        disk: {}
      - name: win10-iso
        bootOrder: 1
        cdrom:
          bus: sata
      - name: virtiocontainerdisk
        cdrom:
          bus: sata
  terminationGracePeriodSeconds: 0
  volumes:
  - name: win10-disk
    persistentVolumeClaim:
      claimName: win10-disk
  - name: win10-iso
    persistentVolumeClaim:
      claimName: win10-iso
  - name: virtiocontainerdisk
    containerDisk:
      image: kubevirt/virtio-container-disk
...
