---
apiVersion: v1
kind: Pod
metadata:
  name: debian
  namespace: default
spec:
  containers:
    - name: pengclone
      image: debian:buster-slim
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - "36000"
      volumeMounts:
        - mountPath: "/mnt"
          name: jijisa-win10
  volumes:
    - name: jijisa-win10
      persistentVolumeClaim:
        claimName: jijisa-win10
...
