apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: pengrixio
  namespace: rook-ceph
spec:
  failureDomain: host
  replicated:
    size: 2
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: pengrixio
provisioner: ceph.rook.io/block
parameters:
  blockPool: pengrixio
  clusterNamespace: rook-ceph
  fstype: xfs
reclaimPolicy: Delete
allowVolumeExpansion: true
